### PR TITLE
create new file:   images/Peacock.jpg

### PR DESCRIPTION
**Pull request by Timing4real**
renamed:    img.bluewater.jpg -> images/img.bluewater.jpg
        modified:   style.css

### CODE REVIEW

**Comment by Timing4real** [comment]
I have done some brush up on css file and html file also added a new image in an images folder created by me.

**Comment by datchibuzor** [comment]
Alright,

Well done sir

**Comment by Timing4real** [comment]
I

**Comment by Timing4real** [comment]
i

**Pull request closed without merging**
